- hosts: all
  become: true
  
  tasks:
      - name: Add the user 'dragon' with a tcsh shell, appending the group 'admins' and 'developers' to the user's groups
        user:
          name: dragon
          shell: /bin/tcsh
          groups: wheel,operator
          append: yes
          expires: -1

      - name: Create a 2048-bit SSH key for user dragon in ~dragon/.ssh/id_rsa
        user:
          name: dragon
          generate_ssh_key: yes
          ssh_key_bits: 2048
          ssh_key_file: .ssh/id_rsa

      - name: Copy make.conf
        copy:
          src: /Users/fanix/Workspace/Git/freebsd-terraform-vultr/src/configs/etc/make.conf
          dest: /etc/make.conf
          owner: root
          group: wheel
          mode: '0644'

      - name: Copy pf.conf
        copy:
          src: /Users/fanix/Workspace/Git/freebsd-terraform-vultr/src/configs/etc/pf.conf
          dest: /etc/pf.conf
          owner: root
          group: wheel
          mode: '0644'
          
      - name: Copy portmaster.rc
        copy:
          src: /Users/fanix/Workspace/Git/freebsd-terraform-vultr/src/configs/etc/portmaster.rc
          dest: /usr/local/etc/portmaster.rc
          owner: root
          group: wheel
          mode: '0644'     
          
      - name: Copy sysctl.conf
        copy:
          src: /Users/fanix/Workspace/Git/freebsd-terraform-vultr/src/configs/etc/sysctl.conf
          dest: /etc/sysctl.conf
          owner: root
          group: wheel
          mode: '0644'
             
      ######################################   
      # ETC Shell Configs
      ######################################  
      - name: Copy /etc/profile
        copy:
          src: /Users/fanix/Workspace/Git/freebsd-terraform-vultr/src/configs/etc/profile
          dest: /etc/profile
          owner: root
          group: wheel
          mode: '0644'      

      - name: Copy /etc/zprofile
        copy:
          src: /Users/fanix/Workspace/Git/freebsd-terraform-vultr/src/configs/etc/zprofile
          dest: /etc/zprofile
          owner: root
          group: wheel
          mode: '0644'

      - name: Copy /etc/zshenv
        copy:
          src: /Users/fanix/Workspace/Git/freebsd-terraform-vultr/src/configs/etc/zshenv
          dest: /etc/zshenv
          owner: root
          group: wheel
          mode: '0644'

      - name: Copy /etc/csh.cshrc
        copy:
          src: /Users/fanix/Workspace/Git/freebsd-terraform-vultr/src/configs/etc/csh.cshrc
          dest: /etc/csh.cshrc
          owner: root
          group: wheel
          mode: '0644'
      ######################################
      #     Bootstraping scripts
      ######################################
      - name: Copy bootstrap.sh
        copy:
          src: /Users/fanix/Workspace/Git/freebsd-terraform-vultr/src/scripts/bootstrap.sh
          dest: /tmp/bootstrap.sh
          owner: root
          group: wheel
          mode: '0700'

      - name: Copy bootstrap-quick.sh
        copy:
          src: /Users/fanix/Workspace/Git/freebsd-terraform-vultr/src/scripts/bootstrap-quick.sh
          dest: /tmp/bootstrap-quick.sh
          owner: root
          group: wheel
          mode: '0700'
      ######################################   
      # USER PROFILES
      ######################################
      - name: (root) Copy .cshrc
        copy:
          src: /Users/fanix/Workspace/Git/freebsd-terraform-vultr/src/configs/dotfiles/.cshrc
          dest: /root/.cshrc
          owner: root
          group: wheel
          mode: '0640'  

      - name: (root) .zshrc
        copy:
          src: /Users/fanix/Workspace/Git/freebsd-terraform-vultr/src/configs/dotfiles/.zshrc
          dest: /tmp/.zshrc
          owner: root
          group: wheel
          mode: '0640'  
 
      - name: (root) .zpath
        copy:
          src: /Users/fanix/Workspace/Git/freebsd-terraform-vultr/src/configs/dotfiles/.zpath
          dest: /root/.zpath
          owner: root
          group: wheel
          mode: '0640'  

      - name: (dragon) Copy .cshrc
        copy:
          src: /Users/fanix/Workspace/Git/freebsd-terraform-vultr/src/configs/dotfiles/.cshrc
          dest: /home/dragon/.cshrc
          owner: dragon
          group: dragon
          mode: '0640'  

      - name: (root) .zpath
        copy:
          src: /Users/fanix/Workspace/Git/freebsd-terraform-vultr/src/configs/dotfiles/.zpath
          dest: /home/dragon/.zpath
          owner: dragon
          group: dragon
          mode: '0640'          